# Waymo Crashes Data

**Author**: Diego Torrealba

**Date Created**: 2026-06-23
**Date Last Modified**: 2026-06-23

Read about where I found the data in the README.

## Import libraries and download data

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
ro_mi_per_location = pd.read_csv("../data/raw/csv1-RO-Miles-per-Location.csv")
ro_mi_per_location = ro_mi_per_location[ro_mi_per_location['County Name'] != "All Locations (mileage blended)"] # get rid of aggregate row

crashes_w_sgo_id_and_group_membership = pd.read_csv("../data/raw/csv2-Crashes-with-SGO-ID-and-Group-Membership.csv")

collision_counts_and_comparison_to_benchmarks = pd.read_csv("../data/raw/csv3-Collision-Counts-and-Comparison-to-Benchmarks.csv")

mi_and_benchmark_crashes_for_dynamic_benchmark = pd.read_csv("../data/raw/csv4-Miles-and-Benchmark-Crashes-for-Dynamic-Benchmark.csv")

### RO-Miles-per-Location

In [26]:
ro_mi_per_location.head(5)

              County Name  Waymo RO Miles (Millions)
0               San Mateo                      3.061
1           San Francisco                     47.906
2  San Francisco Bay Area                     53.520
4                Maricopa                     68.613
5             Santa Clara                      2.554

In [27]:
ro_mi_per_location.shape

(7, 2)

In [28]:
ro_mi_per_location.info()

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   County Name                7 non-null      str
 1   Waymo RO Miles (Millions)  7 non-null      float64
dtypes: float64(1), str(1)
memory usage: 168.0 bytes

### Crashes-with-SGO-ID-and-Group-Membership

In [29]:
crashes_w_sgo_id_and_group_membership.head(5)

,SGO Report ID,SGO Report Version,SGO Amendment,Year Month,State,County,Road Type,Crash Type,Is NHTSA Reportable In-Transport,Is NHTSA Reportable In-Transport Delta-V Less than 1 MPH,Is Police-Reported,Is Any-Injury-Reported,Is Any Vehicle Airbag Deployment,Is Ego Vehicle Airbag Deployment,Is Suspected Serious Injury+,Is Any Fatal Injury,Incident Date,Location Address / Description,Zip Code
0,30270-13564,1.0,Amendment 3,202512,California,San Francisco,Surface Street,Cyclist,True,False,False,False,False,False,False,False,12/28/2025,Polk Street at Pacific Avenue,94109
1,30270-13557,1.0,Amendment 3,202512,Georgia,Fulton,Surface Street,V2V Backing,True,False,False,False,False,False,False,False,12/31/2025,Armour Drive NE near Plasters Avenue,30324
2,30270-13554,1.0,Amendment 3,202512,California,San Mateo,Surface Street,V2V F2R,True,False,False,False,False,False,False,False,12/29/2025,Airport Boulevard near Grand Avenue,94080
3,30270-13549,1.0,Amendment 3,202512,California,Los Angeles,Surface Street,V2V F2R,True,False,False,False,False,False,False,False,12/29/2025,Montana Avenue at S. Barrington Avenue,90049
4,30270-13548,1.0,Amendment 3,202512,Arizona,Maricopa,Surface Street,V2V Lateral,True,False,False,False,False,False,False,False,12/24/2025,N. 56th Street at E. Lafayette Boulevard,85018

In [30]:
crashes_w_sgo_id_and_group_membership.shape

(1390, 19)

In [31]:
crashes_w_sgo_id_and_group_membership.info()

<class 'pandas.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 19 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   SGO Report ID                                             1388 non-null   str
 1   SGO Report Version                                        1388 non-null   float64
 2   SGO Amendment                                             1390 non-null   str
 3   Year Month                                                1390 non-null   int64
 4   State                                                     1390 non-null   str
 5   County                                                    1390 non-null   str
 6   Road Type                                                 1390 non-null   str
 7   Crash Type                                                1390 non-null   str
 8   Is NHTSA Reportable In-Transport                          1390 non-null   bool
 9   Is NHTSA Reportable In-Transport Delta-V Less than 1 MPH  1390 non-null   bool
 10  Is Police-Reported                                        1390 non-null   bool
 11  Is Any-Injury-Reported                                    1390 non-null   bool
 12  Is Any Vehicle Airbag Deployment                          1390 non-null   bool
 13  Is Ego Vehicle Airbag Deployment                          1390 non-null   bool
 14  Is Suspected Serious Injury+                              1390 non-null   bool
 15  Is Any Fatal Injury                                       1390 non-null   bool
 16  Incident Date                                             1390 non-null   str
 17  Location Address / Description                            1390 non-null   str
 18  Zip Code                                                  1390 non-null   str
dtypes: bool(8), float64(1), int64(1), str(9)
memory usage: 130.4 KB

### Collision-Counts-and-Comparison-to-Benchmarks

In [32]:
collision_counts_and_comparison_to_benchmarks.head(5)

,Outcome,Benchmark Comparison,County Name,Grouping Type,Conflict Partner Type Group,Waymo Count,Delta V Less Than 1 Mph Percent,Waymo IPMM,Waymo IPMM CI Lower,Waymo IPMM CI Upper,...,Benchmark IPMM CI Lower,Benchmark IPMM CI Upper,Predicted Benchmark Count,Waymo Count Reduction,Waymo Percent Reduction,Waymo Percent Reduction CI Lower,Waymo Percent Reduction CI Upper,Waymo Rate Ratio,Waymo Rate Ratio CI Lower,Waymo Rate Ratio CI Upper
0,Any Airbag Deployment,Any Airbag Deployment (non-Dynamic),All Locations (mileage blended),All Crashes,All Crashes,48,0.020833,0.281175,0.207316,0.372797,...,1.419534,1.455020,245.346833,197.346833,-0.804359,-0.862165,-0.730851,0.195641,0.137835,0.269149
1,Any Airbag Deployment,Any Airbag Deployment (non-Dynamic),Los Angeles,All Crashes,All Crashes,8,0.000000,0.211319,0.091233,0.416383,...,1.153177,1.177662,44.117927,36.117927,-0.818668,-0.931393,-0.614316,0.181332,0.068607,0.385684
2,Any Airbag Deployment,Any Airbag Deployment (non-Dynamic),Maricopa,All Crashes,All Crashes,19,0.000000,0.276914,0.166720,0.432436,...,1.306042,1.334647,90.589193,71.589193,-0.790262,-0.883088,-0.654062,0.209738,0.116912,0.345938
3,Any Airbag Deployment,Any Airbag Deployment (non-Dynamic),San Francisco,All Crashes,All Crashes,13,0.076923,0.271367,0.144492,0.464047,...,1.698358,1.878033,85.583291,72.583291,-0.848101,-0.926766,-0.722260,0.151899,0.073234,0.277740
4,Any Airbag Deployment,Any Airbag Deployment (non-Dynamic),San Francisco Bay Area,All Crashes,All Crashes,17,0.058824,0.317640,0.185037,0.508572,...,1.631041,1.790858,91.494635,74.494635,-0.814197,-0.900551,-0.684008,0.185803,0.099449,0.315992

In [33]:
collision_counts_and_comparison_to_benchmarks.shape

(1092, 21)

In [23]:
collision_counts_and_comparison_to_benchmarks.info()

<class 'pandas.DataFrame'>
RangeIndex: 1092 entries, 0 to 1091
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Outcome                           1092 non-null   str
 1   Benchmark Comparison              1092 non-null   str
 2   County Name                       1092 non-null   str
 3   Grouping Type                     1092 non-null   str
 4   Conflict Partner Type Group       1092 non-null   str
 5   Waymo Count                       1092 non-null   int64
 6   Delta V Less Than 1 Mph Percent   518 non-null    float64
 7   Waymo IPMM                        1092 non-null   float64
 8   Waymo IPMM CI Lower               1092 non-null   float64
 9   Waymo IPMM CI Upper               1092 non-null   float64
 10  Benchmark IPMM                    1092 non-null   float64
 11  Benchmark IPMM CI Lower           1092 non-null   float64
 12  Benchmark IPMM CI Upper           1092 non-null   float64
 13  Predicted Benchmark Count         1092 non-null   float64
 14  Waymo Count Reduction             1092 non-null   float64
 15  Waymo Percent Reduction           1082 non-null   float64
 16  Waymo Percent Reduction CI Lower  1092 non-null   float64
 17  Waymo Percent Reduction CI Upper  1082 non-null   float64
 18  Waymo Rate Ratio                  1082 non-null   float64
 19  Waymo Rate Ratio CI Lower         1092 non-null   float64
 20  Waymo Rate Ratio CI Upper         1082 non-null   float64
dtypes: float64(15), int64(1), str(5)
memory usage: 179.3 KB

### Miles-and-Benchmark-Crashes-for-Dynamic-Benchmark

In [34]:
mi_and_benchmark_crashes_for_dynamic_benchmark.head(5)

,state_name,county_name,S2 Cell,Outcome,Benchmark Crash Count,HPMS Yearly Vehicle Miles Traveled,Waymo RO Miles
0,Arizona,Maricopa,9739878636298698752,police_reported,24.769229,8.360097e+06,3171.852611
1,Arizona,Maricopa,9739878636298698752,blincoe,49.462419,8.360097e+06,3171.852611
2,Arizona,Maricopa,9739878636298698752,fatal,0.000000,8.360097e+06,3171.852611
3,Arizona,Maricopa,9739878636298698752,ka,4.846153,8.360097e+06,3171.852611
4,Arizona,Maricopa,9739878636298698752,ego_airbag,11.846153,8.360097e+06,3171.852611

In [35]:
mi_and_benchmark_crashes_for_dynamic_benchmark.shape

(14736, 7)

In [ ]:
mi_and_benchmark_crashes_for_dynamic_benchmark.info()

<class 'pandas.DataFrame'>
RangeIndex: 14736 entries, 0 to 14735
Data columns (total 7 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   state_name                          14736 non-null  str
 1   county_name                         14736 non-null  str
 2   S2 Cell                             14736 non-null  uint64
 3   Outcome                             14736 non-null  str
 4   Benchmark Crash Count               14736 non-null  float64
 5   HPMS Yearly Vehicle Miles Traveled  14736 non-null  float64
 6   Waymo RO Miles                      14736 non-null  float64
dtypes: float64(3), str(3), uint64(1)
memory usage: 806.0 KB